# Generated by Django 2.1.1 on 2018-11-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_evv', '0002_auto_20181124_1638'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
